module.exports = {
  siteUrl: "https://www.hackerprank.online",
  ogImage: "https://www.hackerprank.online/assets/crack-desktop.png",
  trustLinks: [
    ["About SimDeck", "/about/"],
    ["Contact", "/contact/"],
    ["Privacy Policy", "/privacy/"],
    ["Terms", "/terms/"],
    ["Safety Disclaimer", "/safety/"],
  ],
  routes: [
    {
      path: "/",
      label: "Hacker Prank Simulation",
      title: "Hacker Prank Simulation | Fake Hacking Simulator Online",
      description: "Run a safe hacker prank simulation in your browser. Try fake hacking screens, phone scans, virus alerts, Windows pranks, and cinematic hacker dashboards.",
      keywords: ["hacker prank", "fake hacking", "hacking prank", "fake hacker prank", "fake hacking website prank"],
      h1: "Hacker Prank Simulation",
      intro: "SimDeck is a safe hacker prank simulation built for videos, demos, streams, and harmless jokes. It creates realistic fake hacking screens without touching real devices, accounts, networks, files, or messages.",
      sections: [
        ["A fake hacking simulator people can actually use", "Search Console data from the previous Cyberlords prank page showed strong demand around hacker prank, fake hacking, hacking prank, fake hacker prank, and fake hacking website prank. This page is built around that intent: people want a convincing screen they can open quickly, make fullscreen, and use as a visual prank without downloads or real hacking."],
        ["What you can launch", "Choose fake phone hacking screens, fake virus scans, email hack theater, Windows update pranks, cracked screen effects, FBI-style lock screens, iOS update loops, Android optimizing screens, and a Windows OS simulator. Each mode is visual only. The buttons, logs, folders, alerts, and progress bars are designed to look alive while staying completely fictional."],
        ["How to use it safely", "Pick a prank folder, customize harmless labels where available, then start the simulation. For best effect, use fullscreen and keep the built-in simulation watermark available when filming or demonstrating. SimDeck is entertainment software, not spyware, malware, phishing, account recovery, or a security bypass tool."],
      ],
      faqs: [
        ["Is this a real hacking tool?", "No. SimDeck is a fake hacking simulator for harmless visual pranks and content creation. It does not access real accounts, devices, messages, cameras, networks, or files."],
        ["Can I use it for a video or livestream?", "Yes. The simulator is designed for demos, videos, streams, and fictional scenes where you need a convincing hacker prank screen."],
        ["Does it work on mobile?", "Yes. Several prank modes are optimized for phones, and the fake phone hacking page includes customizable phone labels."],
      ],
    },
    {
      path: "/hacker-prank/",
      label: "Hacker Prank",
      title: "Hacker Prank | Fake Hacking Simulator Online",
      description: "Open a safe hacker prank online with fake hacking screens, cinematic dashboards, phone scans, virus alerts, and harmless prank modes.",
      keywords: ["hacker prank", "hacking prank", "fake hacker prank", "prank hacker", "fake hacking prank"],
      h1: "Hacker Prank",
      intro: "This hacker prank page is the main launcher for SimDeck. It targets the exact searches that already produced impressions and clicks for the old Cyberlords data: hacker prank, hacking prank, prank hacker, fake hacker prank, and fake hacking prank.",
      sections: [
        ["Built for the search intent", "People searching hacker prank usually want an instant screen they can show to a friend, record for a short video, or use as a fictional computer scene. SimDeck keeps the simulation first, then supports it with clear explanations, safety notes, and links to every prank mode so Google can crawl the full tool set."],
        ["Prank modes included", "The launcher includes fake hacking dashboards, phone scan simulations, fake email access screens, password theater, fake virus scanning, cracked screen visuals, Windows pranks, iOS and Android update loops, and cinematic global network screens. Every mode is a browser animation and does not connect to real systems."],
        ["Why it feels realistic", "The interface uses familiar patterns from terminals, operating systems, security dashboards, process lists, progress bars, folders, and fake command output. Those details create a believable scene while keeping the experience safe and fictional."],
      ],
      faqs: [
        ["What is a hacker prank?", "A hacker prank is a harmless fake screen that looks like hacking software. It is used for entertainment, videos, and jokes, not real access."],
        ["Can I prank someone with it?", "Use it only where the other person will not be harmed, threatened, or tricked into sharing private information. SimDeck includes safety language because it is visual-only entertainment."],
        ["Which prank should I start with?", "Fake phone hacking and fake virus scanner are good first choices because they are easy to understand and visually dramatic."],
      ],
    },
    {
      path: "/fake-phone-hacking/",
      label: "Fake Phone Hacking",
      title: "Fake Phone Hacking Simulator | Phone Hack Prank",
      description: "Launch a fake phone hacking simulator with safe phone scan screens, tracking-style visuals, terminal menus, and customizable phone labels.",
      keywords: ["fake phone hacking", "phone hack prank", "fake phone hacking simulator", "fake hacking screen prank"],
      h1: "Fake Phone Hacking Simulator",
      intro: "The fake phone hacking simulator gives visitors a phone-focused prank flow with customizable labels for phone number, device type, carrier, location, and battery. The details only appear in the fake screen and stay visual.",
      sections: [
        ["Why this page can rank", "Your Search Console data shows strong related demand around fake hacking, fake hacking screen, fake hacking prank, and fake hacking website prank. A dedicated phone page lets SimDeck match more specific long-tail searches while giving users a tool they can start immediately."],
        ["What the phone simulation shows", "The page includes basic scan, phone tracking-style screens, terminal output, Matrix-style code, corporate dashboard visuals, forensic-style reports, prank mode, and data export theater. These screens imitate the look of a scan without collecting or extracting real information."],
        ["How to keep the UI clean", "The simulator remains at the top of the page. Search-friendly text, FAQs, and related links sit below the tool area, so visitors can use the prank without reading a long article first."],
      ],
      faqs: [
        ["Does the phone number get used for anything real?", "No. Any phone number or device label entered is only displayed inside the fake simulation."],
        ["Can it track a real phone?", "No. Tracking screens are visual effects only and do not use GPS, carrier data, or real device access."],
        ["Can I change the iPhone or Android model shown?", "Yes. The simulator can display the device model label you enter before starting the fake scan."],
      ],
    },
    {
      path: "/email-hack-simulator/",
      label: "Email Hack Simulator",
      title: "Fake Email Hack Simulator | Email Prank Tool",
      description: "Run a safe fake email hack simulator with login theater, inbox screens, mailbox folders, recovery alerts, and fictional account activity.",
      keywords: ["email hack simulator", "fake email hack", "email prank simulator", "fake hacking website prank"],
      h1: "Fake Email Hack Simulator",
      intro: "The fake email hack simulator creates account-access theater for fictional scenes. It shows fake login steps, mailbox views, folders, alerts, and recovery-style messages without connecting to real email accounts.",
      sections: [
        ["What this prank is for", "Use this page when you need an email-themed fake hacking screen for a skit, prank video, demo, or cybersecurity awareness moment. It is built to look familiar while avoiding real credentials and real account access."],
        ["How it supports SEO", "Email hack simulator is a narrower topic than hacker prank, which helps the site build topical depth. It links back to the main hacker prank page and to related fake hacking tools so search engines can understand the full prank simulator cluster."],
        ["Safety boundary", "The page should never ask visitors for real email passwords. Any account names, URLs, and messages are fictional labels used inside the browser simulation."],
      ],
      faqs: [
        ["Does this log into email accounts?", "No. It is a fake inbox and fake account-access animation."],
        ["Should users enter real passwords?", "No. The simulation should use fictional labels only."],
        ["Is this useful for cybersecurity demos?", "Yes, as long as it is presented as a visual simulation and not a real compromise."],
      ],
    },
    {
      path: "/fake-virus-scanner/",
      label: "Fake Virus Scanner",
      title: "Fake Virus Scanner Prank | Harmless Security Alert",
      description: "Start a harmless fake virus scanner prank with fictional threat alerts, scan progress, cleanup screens, and security dashboard visuals.",
      keywords: ["fake virus scanner", "virus prank", "fake security scan", "fake hacking prank"],
      h1: "Fake Virus Scanner Prank",
      intro: "The fake virus scanner is a harmless security-style prank that displays fictional threats, scan bars, warning panels, and cleanup progress. It does not scan files or change the device.",
      sections: [
        ["Why it works as a prank", "Virus scanner pranks are easy to understand because most people recognize security alerts and progress bars. SimDeck makes the screen dramatic while clearly keeping the experience fictional and browser-based."],
        ["Best use cases", "Use it for videos, classroom demos, harmless jokes, or fictional support scenes. The page should keep safety text visible in the SEO section so search engines and users understand it is not malware or scareware."],
        ["Related fake hacking tools", "Visitors who like this mode should also find cracked screen prank, hacker prank, Windows update prank, and fake phone hacking through normal links."],
      ],
      faqs: [
        ["Does it scan my computer?", "No. It only displays fake scan progress and fictional alerts."],
        ["Can it remove viruses?", "No. It is not antivirus software."],
        ["Is it safe to open?", "Yes. It runs as a visual browser simulation."],
      ],
    },
    {
      path: "/fake-windows-update/",
      label: "Fake Windows Update",
      title: "Fake Windows Update Prank | Fullscreen Update Screen",
      description: "Open a fake Windows update prank with a realistic update-style screen for harmless jokes, videos, and fullscreen computer pranks.",
      keywords: ["fake Windows update", "Windows update prank", "fake update screen", "computer prank"],
      h1: "Fake Windows Update Prank",
      intro: "The fake Windows update prank gives visitors a familiar update-style screen that can be used for harmless computer jokes and video scenes. It is visual only and does not change system settings.",
      sections: [
        ["A simple computer prank page", "Fake update screens are popular because the idea is instantly recognizable. This page can rank for Windows update prank terms while linking into the broader hacker prank simulation cluster."],
        ["How to use the screen", "Open the page, start the simulation, and switch to fullscreen. The page keeps the real controls available in SimDeck so the user can exit quickly."],
        ["Why this belongs in SimDeck", "It complements the hacker prank and fake virus scanner pages because all three target people looking for safe computer prank visuals."],
      ],
      faqs: [
        ["Will this update Windows?", "No. It is only a fake update screen in the browser."],
        ["Can I exit fullscreen?", "Yes. Use Escape or the SimDeck exit controls."],
        ["Does it work on Mac?", "It runs in the browser, though the visual style is Windows-inspired."],
      ],
    },
    {
      path: "/windows-os-simulator/",
      label: "Windows OS Simulator",
      title: "Windows OS Simulator | XP and Windows 11 Browser Desktop",
      description: "Launch a browser-based Windows OS simulator with XP and Windows 11 modes, working windows, Start menus, desktop icons, and taskbar controls.",
      keywords: ["Windows OS simulator", "Windows XP simulator", "Windows 11 simulator", "fake Windows desktop"],
      h1: "Windows OS Simulator",
      intro: "The Windows OS simulator lets visitors choose between XP-style and modern Windows-style desktops inside the browser. It includes working windows, taskbar controls, Start menus, desktop icons, and apps for realistic prank scenes.",
      sections: [
        ["A tool page, not just a screenshot", "The simulator is interactive. Users can choose the operating system, open apps, move windows, minimize, maximize, and explore the fake desktop. That makes the page stronger than a static image for user engagement."],
        ["SEO role", "This page expands the site beyond broad hacker prank searches into Windows simulator and fake Windows desktop searches. It should be linked from the homepage, hacker prank page, and fake Windows update page."],
        ["Safety and realism", "The simulator copies familiar desktop patterns for entertainment. It does not run Windows, access local files, or change the visitor's operating system."],
      ],
      faqs: [
        ["Is this a real operating system?", "No. It is a browser simulation for visual interaction and pranks."],
        ["Can I choose Windows XP or Windows 11?", "Yes. The simulator includes a chooser for both modes."],
        ["Can windows be minimized and maximized?", "Yes. The fake apps include realistic window controls."],
      ],
    },
    {
      path: "/cracked-screen-prank/",
      label: "Cracked Screen Prank",
      title: "Cracked Screen Prank | Fake Broken Screen Effect",
      description: "Launch a cracked screen prank with fake broken glass overlays for harmless phone, tablet, and desktop screen jokes.",
      keywords: ["cracked screen prank", "broken screen prank", "fake cracked screen", "screen prank"],
      h1: "Cracked Screen Prank",
      intro: "The cracked screen prank displays fake broken glass effects over the browser. It is a visual overlay for harmless jokes and does not damage the screen.",
      sections: [
        ["Why this page matters", "Cracked screen prank is a different search intent from hacker prank, but it fits the same audience: people looking for quick browser-based pranks. It gives the site another crawlable entry point."],
        ["How to use it", "Open the prank, choose the screen effect, and use fullscreen for a more convincing result. The effect is only pixels on the page and can be exited normally."],
        ["Internal linking", "This page should link to fake virus scanner, fake Windows update, and hacker prank because those visitors often want similar visual jokes."],
      ],
      faqs: [
        ["Can this damage my screen?", "No. It is only a fake visual effect in the browser."],
        ["Does it work on phones?", "Yes, it is designed to work on mobile and desktop browsers."],
        ["How do I close it?", "Use the browser controls, Escape, or the SimDeck exit controls."],
      ],
    },
    {
      path: "/fake-fbi-lock-screen/",
      label: "Fake FBI Lock Screen",
      title: "Fake FBI Lock Screen Prank | Fictional Lock Warning",
      description: "Start a fake FBI lock screen prank with fictional warning text, countdown styling, and safe browser-only scare-screen visuals.",
      keywords: ["fake FBI lock screen", "FBI lock screen prank", "fake lock screen", "scare prank"],
      h1: "Fake FBI Lock Screen Prank",
      intro: "The fake FBI lock screen prank is a fictional warning-style screen for harmless scare effects. It is not law enforcement software, ransomware, malware, or a real lock.",
      sections: [
        ["Clear safety positioning", "Because lock screens can feel intense, this page should explain that the warning is fictional and browser-only. That helps users and search engines distinguish it from malware or ransomware content."],
        ["Where it fits", "It belongs in the scare-prank category with fake virus scanner and cracked screen prank. Internal links should connect those pages for better crawl discovery."],
        ["Use responsibly", "Use this only in harmless contexts where it will not cause panic, extortion, or confusion. The page should keep an obvious exit path available."],
      ],
      faqs: [
        ["Is this a real FBI warning?", "No. It is fictional visual content."],
        ["Can it lock my device?", "No. It cannot lock the operating system or files."],
        ["Is it ransomware?", "No. It is a browser prank screen with no real file access."],
      ],
    },
    {
      path: "/ios-update-prank/",
      label: "iOS Update Prank",
      title: "Fake iOS Update Prank | Endless iPhone Update Screen",
      description: "Run a fake iOS update prank with an iPhone-style update loop for harmless mobile jokes and video scenes.",
      keywords: ["iOS update prank", "fake iPhone update", "fake iOS update", "mobile prank"],
      h1: "Fake iOS Update Prank",
      intro: "The fake iOS update prank shows an iPhone-style update screen in the browser. It is designed for harmless mobile jokes and does not install software.",
      sections: [
        ["Mobile-first prank intent", "Your device data shows mobile has a stronger CTR than desktop, so mobile prank pages deserve focused content and clean layouts. This page gives iPhone-style search intent its own target."],
        ["How it behaves", "The update screen is a looped visual. It can be used in fullscreen or in a phone browser for short pranks and videos."],
        ["Related pages", "Linking this page to fake phone hacking and Android optimizing prank helps Google understand the mobile prank cluster."],
      ],
      faqs: [
        ["Does this update my iPhone?", "No. It is only a fake browser screen."],
        ["Does it work on Android?", "It can open in any browser, but the visual style is iOS-inspired."],
        ["Can I stop the loop?", "Yes. Use the normal browser or SimDeck exit controls."],
      ],
    },
    {
      path: "/android-optimizing-prank/",
      label: "Android Optimizing Prank",
      title: "Android Optimizing Prank | Fake Android Repair Screen",
      description: "Open a fake Android optimizing prank with repair, cache, system loop, and harmless mobile device visuals.",
      keywords: ["Android optimizing prank", "fake Android repair", "Android prank", "mobile prank"],
      h1: "Android Optimizing Prank",
      intro: "The Android optimizing prank displays fake repair, cache, and system optimizing screens. It is a harmless browser simulation and does not change phone settings.",
      sections: [
        ["Why Android gets its own page", "Mobile queries can convert well because visitors often want to run the prank directly on a phone. A dedicated Android page supports that intent and links into the phone hacking simulator page."],
        ["What it shows", "The screen imitates device maintenance patterns such as optimizing apps, repairing cache, and checking system status. All messages are fictional."],
        ["How it supports the site cluster", "Together with fake phone hacking and fake iOS update, this page creates a stronger mobile prank section for SimDeck."],
      ],
      faqs: [
        ["Does it repair my Android phone?", "No. It only displays fake optimizing messages."],
        ["Can it delete data?", "No. It has no access to phone files."],
        ["Is it safe for mobile browsers?", "Yes. It is a visual web page."],
      ],
    },
  ],
};
